name: Build and Test
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: write 

jobs:
  configure:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Pull request auto merge enabler
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        uses: poad/github-pull-request-auto-merge-enable-action@v2.1.0
        with:
          pull_request_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
          repository: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          merge_method: SQUASH

  test:
    strategy:
      matrix:
        deno: ["v1.x", "canary"]

    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Run build
        working-directory: aleph-example
        run:  deno
